version: '3'
services:
  java-srv:
    build: java-srv
    ports:
      - "80:8080"
    command: sh -c "/wait && mvn clean spring-boot:run"
    environment:
      - WAIT_HOSTS=gf-locator:10334,db-1:40404,db-2:40404
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  gf-locator:
    image: gemfire/gemfire
    environment:
      - ACCEPT_TERMS=y
    command: sh -c "gfsh start locator --name=gf-locator && /geode/script/forever.sh"
    volumes:
      - ./db:/geode/script
    ports:
      - 10334 # locator port

  db-1:
    image: gemfire/gemfire
    environment:
      - ACCEPT_TERMS=y
    command: sh -c "gfsh start server --name=server1 --locators=gf-locator\[10334\] && /geode/script/forever.sh"
    volumes:
      - ./db:/geode/script
    ports:
      - 40404 # cache port

  db-2:
    image: gemfire/gemfire
    environment:
      - ACCEPT_TERMS=y
    command: sh -c "gfsh start server --name=server2 --locators=gf-locator\[10334\] && /geode/script/forever.sh"
    volumes:
      - ./db:/geode/script
    ports:
      - 40404 # cache port
